### ISSUE TITLE
how to support package Redfish-Tacklebox to exe via pyinstaller

### ISSUE THREAD

**Issue by PeterKchen2** [DMTF/Redfish-Tacklebox#107]
how to support package Redfish-Tacklebox to exe via pyinstaller

**Comment by mraineri** [comment]
Right now our deployment path is to use pip to install the scripts to your Python installation's "scripts" directory, and (assuming your PATH variable includes the scripts directory) you can run it natively in your shell. Is there a need to also create executables for each of the scripts?

I haven't validated this yet, but I believe you can do something like this for each script in the scripts directory if you really need an exe file:

`pyinstaller -F -w -n rf_accounts.exe scripts/rf_accounts.py`

**Comment by PeterKchen2** [comment]
3Q

**Comment by PeterKchen2** [comment]
Dear mraineri 

I create a pull request for this issue

#issue 106 and issue #107 implement

**Comment by PeterKchen2** [comment]
Dear mraineri

I create a pull request for this issue

https://github.com/DMTF/Redfish-Tacklebox/pull/117

**Comment by PeterKchen2** [comment]
Can you feedback about this modify

**Comment by mraineri** [comment]
PR merged; closing.
