### ISSUE TITLE
AMI redfish server systems's boot property is in /redfish/v1/Systems/Self/SD

### ISSUE THREAD

**Issue by PeterKchen2** [DMTF/Redfish-Tacklebox#111]
AMI redfish server systems's boot property is in /redfish/v1/Systems/Self/SD

and if want to set boot property attribute, 
must send PATCH in /redfish/v1/Systems/Self/SD, not send PATCH in /redfish/v1/Systems/Self

Detail is below

/redfish/v1/Systems/Self response:
[System_Self.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168525/System_Self.txt)

/redfish/v1/Systems/Self/SD response:
[Systems_Self_SD.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168529/Systems_Self_SD.txt)

**Comment by PeterKchen2** [comment]
Any suggestion about this issue

**Comment by mraineri** [comment]
This might be a case of adding another "workaround" indicator to bypass service issues like this. I need to think about this one a little bit more.

But in general, I wouldn't expect services to require applying boot override properties to the settings resource. The reason for this is the semantics of the boot override properties are always "this is what we'll attempt on the next boot", so putting this in a settings resource can add confusion about how this will be handled; it could be interpreted that two reboots are required for the override to take place. So, I think it would be worth providing feedback to your vendor about this.

**Comment by PeterKchen2** [comment]
thank you

**Comment by PeterKchen2** [comment]
I want to question when redfish need this like url is /SD

**Comment by mraineri** [comment]
Understood that's what they documented and implemented. However, that goes against best practices and they should change their behavior.

**Comment by PeterKchen2** [comment]
they currently don't want to change this behavior, how to fix this contition

**Comment by mraineri** [comment]
They need to bring this up to us; AMI is a member of DMTF and the Redfish Forum and can participate directly. The rest of the industry is in disagreement with them, and existing tools in non-DMTF projects do not support what AMI is doing.

**Comment by jcleung5549** [comment]
If we're supporting non-conformant behavior, I think we need a --flag that signifies that.

**Comment by mraineri** [comment]
Yes, that's exactly what `--workaround` is for.

**Comment by plmanik** [comment]
> They need to bring this up to us; AMI is a member of DMTF and the Redfish Forum and can participate directly. The rest of the industry is in disagreement with them, and existing tools in non-DMTF projects (such as OpenStack Ironic and Ansible) do not support what AMI is doing.

@mraineri AMI discussed this in DMTF forum already https://redfishforum.com/thread/627/bootsourceoverrideenabled-usage-computersystems-instance, since the usage of current boot is not clear and it was different in different interface, so hold of making this changes

**Comment by jcleung5549** [comment]
@plmanik, the link you cited is the public Redfish discussion site.  Mike is reference to DMTF Redfish Forum, of which AMI is a member.  Although most queries on the discussion site can be handled quickly, Mike's has the option and discretion to bring the discussion into the Redfish Forum. He has done so in this case. As a member, AMI is encouraged to attend.

**Comment by plmanik** [comment]
> @plmanik, the link you cited is the public Redfish discussion site. Mike is reference to DMTF Redfish Forum, of which AMI is a member. Although most queries on the discussion site can be handled quickly, Mike's has the option and discretion to bring the discussion into the Redfish Forum. He has done so in this case. As a member, AMI is encouraged to attend.
@jcleung5549 Are you asking to post to https://github.com/DMTF/Redfish/issues/, please confirm

**Comment by jcleung5549** [comment]
I've made no such request.  (Why do you include comment in your comment - very distracting.)

**Comment by plmanik** [comment]
I tried Quote reply based on your comments and I can remove

**Comment by jautor** [comment]
> 
> @mraineri AMI discussed this in DMTF forum already https://redfishforum.com/thread/627/bootsourceoverrideenabled-usage-computersystems-instance, since the usage of current boot is not clear and it was different in different interface, so hold of making this changes

@plmanik I'm not sure what you're referring to in that thread, but the concept of a "one time boot order (source) override" pre-dates Redfish, and is absolutely expected to affect the NEXT boot.  The entire purpose is to kick off a repair / diagnostics/ re-deployment process, not make permanent changes to the system's configuration.  I would fully expect there is ancient IPMI support for this functionality already - and the Redfish properties are just providing another means of using that BMC feature (which absolutely has to be communicated to BIOS to actually perform).

Having that property in a Redfish Settings resource would indicate that the "setting" would be applied at the next reset (boot), which would then indicate that the boot AFTER that would be when the override would take place, and that is definitely not anyone's expectation.
