### ISSUE TITLE
some PATCH/POST action need to add workaround case below, but I don' t known how to handle it

### ISSUE THREAD

**Issue by PeterKchen2** [DMTF/Redfish-Tacklebox#128]
detail in below:

https://redfishforum.com/thread/905/question-oem-propety

**Comment by mraineri** [comment]
This one is going to take some extra thought... I don't have an easy recipe for how to make generic workaround logic for this one, but I'll try to think of something...

**Comment by PeterKchen2** [comment]
I think this case need require ami do not use such as design as redfish api
