### ISSUE TITLE
 rf_boot_override.py comamnd throws 500 internal error if one of our machine is in OFF state

### ISSUE THREAD

**Issue by rajeshkumarmhpe** [DMTF/Redfish-Tacklebox#143]
rf_boot_override.py command throws 500 internal error if one of our machine is in OFF state.If its in ON state then no 500 internal error is seen.

Note:
Other two machines(platforms ) working fine even if its in ON/OFF state it doesnt matter.

python3 rf_boot_override.py --user uuuuuu --password pppppp --rhost https://10.x.x.x --system Partition0 -uefi UefiTarget -reset  -t UefiShell

Setting a one time boot for UefiShell...
Resetting the system...
Task is Done!
Operation failed: HTTP 500
A general error has occurred.  See Resolution for information on how to resolve the error, or @Message.ExtendedInfo if Resolution is not provided.
The request failed due to an internal service error.  The service is still operational.

**Comment by mraineri** [comment]
Can you try again with `--debug` added to the command line and provide the .log file generated?

It sounds like your service is requiring the system to be in a particular state for that reset option (which goes against guidance in the Redfish Spec). The log file will help confirm that.

**Comment by rajeshkumarmhpe** [comment]
Please find the attached debug log for your reference.
[rf_boot_override-2024-04-11-211939.log](https://github.com/DMTF/Redfish-Tacklebox/files/14954082/rf_boot_override-2024-04-11-211939.log)

**Comment by mraineri** [comment]
The trace does show this is a service-side issue. However the error response is not particularly useful from this system; it just says "A general error has occurred".

The tool is behaving correctly and this would need to be fixed on the system. If the issue with this system is unique to it being in the powered off state, then that's a clear indicator that the service isn't following guidance from the Redfish Specification.

**Comment by mraineri** [comment]
Closing; issue needs to be resolved by the service since it's not following guidance from the Redfish spec.
