### ISSUE TITLE
rf_manager_config.py returned error while tryig to run with option 'getnet'

### ISSUE THREAD

**Issue by gumpana** [DMTF/Redfish-Tacklebox#158]
python3 rf_manager_config.py -u <username> -p <password> -r https://<IP>/ getnet -i 1
Ethernet Interface 1 Info
  InterfaceEnabled: True
  LinkStatus: LinkUp
  MACAddress: <mac address>
  PermanentMACAddress: <mac address>
  HostName: <hostname>
  FQDN: None
  NameServers: <name servers>
_sequence item 0: expected str instance, NoneType found_

**Comment by mraineri** [comment]
Can you run with `-debug` and send the output?

**Comment by mraineri** [comment]
I suspect it's because there's something like this in the response for StaticNameServers:

```
{
    "StaticNameServers": [ null, null, null, null ]
}
```

This is valid in the service, but I can see how the output is constructed it's not handling the null padding properly. The debug output will confirm this.

**Comment by mraineri** [comment]
There should be a log file saved in the working directory when you run the command. Can you share that file?

**Comment by mraineri** [comment]
Thanks, that confirms my suspicion; I'll have a fix this week for it.
