### ISSUE TITLE
Would like a logservice tool

### ISSUE THREAD

**Issue by frsauvage** [DMTF/Redfish-Tacklebox#26]
Would like a tool to view logs from Logservice

rf_logs -u <user> -p <password> -r <rhost> -s <system_id> -m <manager_id> -c <chassis>

The -u, -p, and -r arguments are the same as other tools (and all required).
The -s argument will target a specified system. optional.
The -m argument will target a specified manager. optional.
The -c argument will target a specified chassis. optional.

If no optional parameter is provided => error, at least one.

I may miss options ?

Best Regards,
Francine

**Comment by mraineri** [comment]
I've been thinking about making a tool like this for some time now and have not had a chance to work on it. The arguments you're proposing look good to me; we might need an additional "log service" argument so specify which log (managers, systems, and chassis can each have multiple log services).

**Comment by frsauvage** [comment]
Hi @mraineri , so happy you agree with me :-)
Thanks, I care a lot about logs ,so  I would be grateful if you add it,

Best Regards,
Francine

**Comment by bb-Ricardo** [comment]
Maybe you could give this a try: https://github.com/bb-Ricardo/check_redfish
