### ISSUE TITLE
Push model firmware update

### ISSUE THREAD

**Issue by mgarrett33** [DMTF/Redfish-Tacklebox#27]
It would be good to update the firmware update tool with options to perform the "push" style update.  This would issue the multipart mime POST format and track the status to completion.

This is desirable to avoid having to fire up a web server.

**Comment by mraineri** [comment]
I agree; I'd like to bake it into the existing update tool. Right now it spins up a local webserver if the user specifies a local file, but we can first check if the multi part URI is supported.

Essentially...
```
If specified file is remote, use SimpleUpdate
Else
    If multi part is supported, send the image using POST to the multi part URI
    Else use local webserver to host image
```

**Comment by mgarrett33** [comment]
I completely agree with that approach.
