### ISSUE TITLE
cannot add user to lenovo servers ( ThinkSystem SR530,630,650)

### ISSUE THREAD

**Issue by mykolq** [DMTF/Redfish-Tacklebox#42]
Hello. i'm trying to add new user to lenovo server, but have an error:
`redfish_utilities.accounts.RedfishAccountNotAddedError: Failed to add user 'test'; user may already exist or there is not enough space for the new user.`
Response is:
```
'500
Date Fri, 03 Jul 2020 12:37:48 GMT
Content-Type application/json
Transfer-Encoding chunked
Connection keep-alive
Content-Language en
OData-Version 4.0
Cache-Control no-store
Server XCC Web Server
Strict-Transport-Security max-age=31536000; includeSubDomains

{"error":{"@Message.ExtendedInfo":[{"MessageArgs":[],"Resolution":"Resubmit the request.  If the problem persists, consider resetting the service.","MessageId":"Base.1.6.InternalError","Severity":"Critical","Message":"The request failed due to an internal service error.  The service is still operational.","@odata.type":"#Message.v1_0_8.Message"}],"code":"Base.1.6.GeneralError","message":"A general error has occurred. See ExtendedInfo for more information."}}
```
My command is:
`rf_accounts.py --user USERID --password USERKVM00! --rhost https://10.81.4.34 --add zabbix '1qaz@WSX#EDC' Read-only`

Server OS: CentOS Linux release 8.2.2004 (Core)
Python version: Python 3.6.8 
redfish-utilities version: 1.0.7

**Comment by billdodd** [comment]
`Read-only` is not one of the standard roles. Try changing your command to use `ReadOnly`.

**Comment by mykolq** [comment]
> `Read-only` is not one of the standard roles. Try changing your command to use `ReadOnly`.

i am stupid. THanks for help

**Comment by mraineri** [comment]
Closing; user error in this case.

Please file a new issue if other problems crop up.
