### ISSUE TITLE
Problem with rf_bios_settings.py

### ISSUE THREAD

**Issue by ryantig** [DMTF/Redfish-Tacklebox#55]
I'm not able to view / set any bios attributes with the command:
```
rf_bios_settings.py -u admin -p admin -r https://192.168.0.99 -s Self
Traceback (most recent call last):
  File "/usr/local/bin/rf_bios_settings.py", line 33, in <module>
    current_settings, future_settings = redfish_utilities.get_system_bios( redfish_obj, args.system )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/systems.py", line 518, in get_system_bios
    bios_settings = context.get( bios.dict["@Redfish.Settings"]["SettingsObject"]["@odata.id"] )
KeyError: 'SettingsObject'
```
If I use redfishtool with raw GET /redfish/v1/Systems/Self/Bios, does return all the Attributes, but is less clear on patch command etc.

Any thoughts?  Thanks!
```
pip3 show redfish_utilities redfish
Name: redfish-utilities
Version: 1.1.4
Summary: Redfish Utilities
Home-page: https://github.com/DMTF/Redfish-Tacklebox
Author: DMTF, https://www.dmtf.org/standards/feedback
Author-email: None
License: BSD 3-clause "New" or "Revised License"
Location: /usr/local/lib/python3.9/dist-packages
Requires: redfish
Required-by:
---
Name: redfish
Version: 3.0.1
Summary: Redfish Python Library
Home-page: https://github.com/DMTF/python-redfish-library
Author: DMTF, https://www.dmtf.org/standards/feedback
Author-email: None
License: BSD 3-clause "New" or "Revised License"
Location: /usr/local/lib/python3.9/dist-packages
Requires: jsonpatch, jsonpointer, jsonpath-rw
Required-by: redfish-utilities
```

**Comment by mraineri** [comment]
Can you show me the response payload you get when you do a GET on "/redfish/v1/Systems/Self/Bios"? From the description of the problem, it looks like the system you're using does *not* have a Settings resource. I've never seen Bios implemented this way. "Settings" is used to contain property values that take effect at a future point in time, and the semantics of not having that for Bios means that the settings are taking effect immediately.

**Comment by mraineri** [comment]
Looking at the trace a bit more, there are checks for `@Redfish.Settings` in the payload, and won't proceed to the Settings resource unless it finds that property. It might be the implementation did not render the `@Redfish.Settings` object correctly in the payload (and the output you get from redfishtool will help confirm that).

**Comment by ryantig** [comment]
You nailed it 👍 .Thanks  Same root cause pescobar found + workaround in [redfishforums](https://redfishforum.com/thread/429/find-url-update-bios-settings). This implementation doesn't provide the settings object :(.
  "@Redfish.Settings": {
    "@odata.type": "#Settings.v1_2_0.Settings",
    "ETag": "Dummyetag",
    "Messages": [
      {
        "MessageId": "Base.1.0.SettingsFailed"
      }
    ]
  }
For rf_bios_settings.py, I'd think even if there isn't a proper reference field for making the changes, without the flag to make a change, I'd think it would still be possible and helpful good to have it walk the Attributes within the AttributeRegistry and output the names + values. ?
+ Maybe report that the implementation is not providing the expected @redfish.Settings object. ?  It would help redfish newbs like myself to find the right search terms to find the issue. :)

FWIW I worked around the particular change I wanted to make using httpie, based on the pescobar workaround, like this:
`echo '{"Attributes": {"EMAG0000": true}}' | http --verify=no --auth admin:password PATCH https://192.168.0.99/redfish/v1/Systems/Self/Bios/SD If-None-Match:"123456"`
HTTP/1.1 204 No Content
Allow: GET, PUT, PATCH, POST
Content-Type: text/html; charset=UTF-8
Date: Wed, 14 Jul 2021 22:43:56 GMT
Server: AMI MegaRAC Redfish Service
Doing a reboot on the server after that got the change active.

**Comment by mraineri** [comment]
I can certainly see value in making the exception messages more clear with regards to missing properties that are expected to be there to help highlight the problem is with the service and not the user. I'll need to think about good methods for doing that without bloating the code since the tools in this project do make many assumptions about the presence of properties (such as services always rendering the mandatory `Members` property in resource collections).

I'll also need to think about how to show the current BIOS attributes gracefully without conflicting with logic that reports errors about the implementation.

Definitely all good ideas.

**Comment by ryantig** [comment]
FWIW Full GET below (sorry, should have included full output on prior note).  I'd think if not looking to change, just outputting the json section within `Attributes` would work to show settings (read only), but since I only saw this non specification compliant rev, that wouldn't be doable on a proper implementation where `@Redfish.Settings` reference is used correctly. ?  Thanks for considering some way to flag it even if it doesn't output the attributes on broken  implementations.  Either way, future google searches might land on this to help find the workaround :)

`http --verify no --auth admin:password https://$IP/redfish/v1/Systems/Self/Bios`
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: X-Auth-Token
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Auth-Token
Allow: GET
Cache-Control: no-cache, must-revalidate
Content-Length: 2837
Content-Type: application/json; charset=UTF-8
Date: Fri, 16 Jul 2021 01:37:01 GMT
ETag: W/"1626303995"
Link: <http://redfish.dmtf.org/schemas/v1/Bios.v1_1_0.json>; rel=describedby
OData-Version: 4.0
Server: AMI MegaRAC Redfish Service

{
    "@Redfish.Settings": {
        "@odata.type": "#Settings.v1_2_0.Settings",
        "ETag": "Dummyetag",
        "Messages": [
            {
                "MessageId": "Base.1.0.SettingsFailed"
            }
        ]
    },
    "@odata.context": "/redfish/v1/$metadata#Bios.Bios",
    "@odata.etag": "W/\"1626303995\"",
    "@odata.id": "/redfish/v1/Systems/Self/Bios",
    "@odata.type": "#Bios.v1_1_0.Bios",
    "Actions": {
        "#Bios.ChangePassword": {
            "@Redfish.ActionInfo": "/redfish/v1/Systems/Self/Bios/ChangePasswordActionInfo",
            "target": "/redfish/v1/Systems/Self/Bios/Actions/Bios.ChangePassword"
        },
        "#Bios.ResetBios": {
            "@Redfish.ActionInfo": "/redfish/v1/Systems/Self/Bios/ResetBiosActionInfo",
            "target": "/redfish/v1/Systems/Self/Bios/Actions/Bios.ResetBios"
        }
    },
    "AttributeRegistry": "BiosAttributeRegistry",
    "Attributes": {
        "EMAG0000": true,
        "EMAG0001": true,
        "EMAG0002": true,
        "EMAG0003": true,
        "EMAG0004": false,
        "EMAG0007": false,
        "EMAG0008": "Disable",
        "EMAGSERIAL000": true,
        "EMAGSERIAL001": true,
        "FBO201": "UEFI Hard Disk",
        "FBO202": "UEFI Network",
        "FBO203": "UEFI CD/DVD",
        "FBO204": "UEFI USB Device",
        "FBO205": "UEFI AP",
        "GBT0200": "Last State",
        "IPMI000": "Enabled",
        "IPMI001": "No",
        "IPMI002": "Do Nothing",
        "IPMI003": "Error code",
        "MAPIDS": "TCG003:0,TCG023:1,TCG001:1,TCG006:1,TCG004:1,TCG002:1,TCG017:1,TCG018:1,TCG019:1,TCG020:1,TCG021:1,TCG007:1,TCG011:1,TCG012:1,TCG013:1,TCG010:1,TCG022:1,TCG014:1,EMAG0000:0,EMAG0001:0,EMAG0004:1,EMAG0002:0,EMAG0003:1,EMAG0008:0,EMAG0007:0,TER001:1,TER010:1,TER06B:1,TER011:0,TER0020:0,TER05C:0,TER02F:0,TER03E:0,TER04D:0,TER012:0,TER0021:0,TER030:0,TER03F:0,TER04E:0,TER05D:0,TER07B:0,TER089:0,TER06c:0,TER098:0,PRC0002:0,PRC0003:0,PRC0001:0,USB003:1,USB00F:1,NWSK000:0,NWSK001:0,NWSK006:0,NWSK002:0,NWSK007:0,NWSK003:1,NWSK004:0,NWSK005:0,GBT0200:0,EMAGSERIAL000:0,EMAGSERIAL001:0,SETUP001:0,SETUP002:0,SETUP003:0,SETUP004:0,SETUP005:0,SETUP008:0,FBO201:1,FBO202:1,FBO203:1,FBO204:1,FBO205:1,IPMI000:1,IPMI001:0,IPMI002:0,IPMI003:0,",
        "NWSK000": "Enabled",
        "NWSK001": "Enabled",
        "NWSK002": "Disabled",
        "NWSK003": "Enabled",
        "NWSK004": 1,
        "NWSK005": 1,
        "NWSK006": "Disabled",
        "NWSK007": "Disabled",
        "PRC0001": "Enabled",
        "PRC0002": "Enabled",
        "PRC0003": "1",
        "SETUP001": null,
        "SETUP002": null,
        "SETUP003": 5,
        "SETUP004": "On",
        "SETUP005": true,
        "SETUP008": "Place First",
        "TCG001": "Enabled",
        "TCG002": "Enabled",
        "TCG003": "Enable",
        "TCG004": "Enable",
        "TCG006": "None",
        "TCG007": "None",
        "TCG010": "TCG_2",
        "TCG011": "Enabled",
        "TCG012": "Enabled",
        "TCG013": "Enabled",
        "TCG014": "CRB",
        "TCG017": "Enabled",
        "TCG018": "Enabled",
        "TCG019": "Disabled",
        "TCG020": "Disabled",
        "TCG021": "Disabled",
        "TCG022": "1.3",
        "TCG023": "Disabled",
        "TER001": true,
        "TER0020": "115200",
        "TER0021": "115200",
        "TER010": true,
        "TER011": "VT100+",
        "TER012": "VT100+",
        "TER030": "8",
        "TER03F": "None",
        "TER04E": "1",
        "TER05C": "None",
        "TER05D": "None",
        "TER06B": "COM1 / SOL",
        "TER06c": true,
        "TER07B": true,
        "TER089": false,
        "TER098": "ESCN",
        "USB003": "Enabled",
        "USB00F": "Enabled"
    },
    "Description": "Current BIOS Settings",
    "Id": "Bios",
    "Name": "Current BIOS Settings"
}

**Comment by mraineri** [comment]
@ryantig I discussed this issue with a few others and we're thinking of taking a slightly different approach. The error reporting is enhanced to make it clear that there is an issue with the service and the vendor needs to correct the issue, but we'd like to add a "workaround" flag to try to automatically account for this type of behavior. Are you able to test the "Fix55-Enhancing-Error-Reporting-for-BIOS" branch to see if that helps you out? Would like to get feedback from folks outside the group to see if the error reporting helps guide you to next steps.

**Comment by ryantig** [comment]
@mraineri Will give it a pull+try and update soon. thanks!

**Comment by mraineri** [comment]
Thanks for testing it out. Can you verify if you can perform a GET on the "SD" resource? I'm concerned they might only allow PATCH.

If "SD" on that system only supports PATCH, then the workaround I discussed with others unfortunately will not work and we'll need to think of alternatives...

**Comment by mraineri** [comment]
And just be be clear, try performing a GET on `https://{IP}/redfish/v1/Systems/Self/Bios/SD`

**Comment by ryantig** [comment]
Ah, yes, /SD will only take PATCH, GET fails. :(
`http --verify=no --auth ${U}:${P} GET "https://${IP}/redfish/v1/Systems/Self/Bios/SD"`
HTTP/1.1 404 Not Found
Content-Length: 497
Content-Type: application/json; charset=UTF-8
Date: Thu, 22 Jul 2021 01:58:26 GMT
OData-Version: 4.0
Server: AMI MegaRAC Redfish Service

{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "@odata.type": "#Message.v1_0_8.Message",
                "Message": "The resource at the URI /redfish/v1/Systems/Self/Bios/SD was not found.",
                "MessageArgs": [
                    "/redfish/v1/Systems/Self/Bios/SD"
                ],
                "MessageId": "Base.1.5.ResourceMissingAtURI",
                "Resolution": "Place a valid resource at the URI or correct the URI and resubmit the request.",
                "Severity": "Critical"
            }
        ],
        "code": "Base.1.5.ResourceMissingAtURI",
        "message": "The resource at the URI /redfish/v1/Systems/Self/Bios/SD was not found."
    }
}

**Comment by mraineri** [comment]
Thanks for confirming; I'll add some additional workaround logic to at least have the "display" functionality working.

**Comment by mraineri** [comment]
@ryantig I made additional changes in that branch so that you can at least read the current BIOS settings. Can you please give it a try on your system to confirm it works for you?

**Comment by mraineri** [comment]
@ryantig did you have a chance to confirm the changes? The work well on the systems I have available, but it would be good to have confirmation that it's good for you too.

**Comment by ryantig** [comment]
@mraineri So sorry for the delay!  It now works with --workaround, providing nicely formatted data, and the data that it's out of spec, etc - great output, thanks!
```
rf_bios_settings.py -u $U -p $P -r https://$IP --workaround
/opt/homebrew/lib/python3.9/site-packages/redfish_utilities/systems.py:607: UserWarning: System 'Self' BIOS resource contains the settings term, but no 'SettingsObject'.  Contact your vendor.  Attempting workarounds...
  warnings.warn( "System '{}' BIOS resource contains the settings term, but no 'SettingsObject'.  Contact your vendor.  Attempting workarounds...".format( system_id ) )
/opt/homebrew/lib/python3.9/site-packages/redfish_utilities/systems.py:546: UserWarning: System 'None' BIOS resource contains the settings term, but no 'SettingsObject'.  Contact your vendor.  Workarounds exhausted for reading the settings data and falling back on using the active attributes.
  warnings.warn( "System '{}' BIOS resource contains the settings term, but no 'SettingsObject'.  Contact your vendor.  Workarounds exhausted for reading the settings data and falling back on using the active attributes.".format( system_id ) )

BIOS Settings:
  Attribute Name                 | Current Setting                | Future Setting
  EMAG0000                       | True                           | True
  EMAG0001                       | True                           | True
  EMAG0002                       | True                           | True
  EMAG0003                       | True                           | True
  EMAG0004                       | False                          | False
  EMAG0007                       | False                          | False
  EMAG0008                       | Disable                        | Disable
  EMAGSERIAL000                  | True                           | True
  EMAGSERIAL001                  | True                           | True
  FBO201                         | UEFI USB Device                | UEFI USB Device
  FBO202                         | UEFI Hard Disk                 | UEFI Hard Disk
  FBO203                         | UEFI AP                        | UEFI AP
  FBO204                         | UEFI Network                   | UEFI Network
  FBO205                         | UEFI CD/DVD                    | UEFI CD/DVD
  GBT0200                        | Last State                     | Last State
  IPMI000                        | Enabled                        | Enabled
  IPMI001                        | No                             | No
  IPMI002                        | Do Nothing                     | Do Nothing
  IPMI003                        | Error code                     | Error code
  MAPIDS                         | TCG003:0,TCG023:1,TCG001:1,TCG006:1,TCG004:1,TCG002:1,TCG017:1,TCG018:1,TCG019:1,TCG020:1,TCG021:1,TCG007:1,TCG011:1,TCG012:1,TCG013:1,TCG010:1,TCG022:1,TCG014:1,EMAG0000:0,EMAG0001:0,EMAG0004:1,EMAG0002:0,EMAG0003:1,EMAG0008:0,EMAG0007:0,TER001:1,TER010:1,TER06B:1,TER011:0,TER0020:0,TER05C:0,TER02F:0,TER03E:0,TER04D:0,TER012:0,TER0021:0,TER030:0,TER03F:0,TER04E:0,TER05D:0,TER07B:0,TER089:0,TER06c:0,TER098:0,PRC0002:0,PRC0003:0,PRC0001:0,USB003:1,USB00F:1,NWSK000:0,NWSK001:0,NWSK006:0,NWSK002:0,NWSK007:0,NWSK003:1,NWSK004:0,NWSK005:0,GBT0200:0,EMAGSERIAL000:0,EMAGSERIAL001:0,SETUP001:0,SETUP002:0,SETUP003:0,SETUP004:0,SETUP005:0,SETUP008:0,FBO201:1,FBO202:1,FBO203:1,FBO204:1,FBO205:1,IPMI000:1,IPMI001:0,IPMI002:0,IPMI003:0, | TCG003:0,TCG023:1,TCG001:1,TCG006:1,TCG004:1,TCG002:1,TCG017:1,TCG018:1,TCG019:1,TCG020:1,TCG021:1,TCG007:1,TCG011:1,TCG012:1,TCG013:1,TCG010:1,TCG022:1,TCG014:1,EMAG0000:0,EMAG0001:0,EMAG0004:1,EMAG0002:0,EMAG0003:1,EMAG0008:0,EMAG0007:0,TER001:1,TER010:1,TER06B:1,TER011:0,TER0020:0,TER05C:0,TER02F:0,TER03E:0,TER04D:0,TER012:0,TER0021:0,TER030:0,TER03F:0,TER04E:0,TER05D:0,TER07B:0,TER089:0,TER06c:0,TER098:0,PRC0002:0,PRC0003:0,PRC0001:0,USB003:1,USB00F:1,NWSK000:0,NWSK001:0,NWSK006:0,NWSK002:0,NWSK007:0,NWSK003:1,NWSK004:0,NWSK005:0,GBT0200:0,EMAGSERIAL000:0,EMAGSERIAL001:0,SETUP001:0,SETUP002:0,SETUP003:0,SETUP004:0,SETUP005:0,SETUP008:0,FBO201:1,FBO202:1,FBO203:1,FBO204:1,FBO205:1,IPMI000:1,IPMI001:0,IPMI002:0,IPMI003:0,
  NWSK000                        | Enabled                        | Enabled
  NWSK001                        | Enabled                        | Enabled
  NWSK002                        | Disabled                       | Disabled
  NWSK003                        | Enabled                        | Enabled
  NWSK004                        | 1                              | 1
  NWSK005                        | 1                              | 1
  NWSK006                        | Disabled                       | Disabled
  NWSK007                        | Disabled                       | Disabled
  PRC0001                        | Enabled                        | Enabled
  PRC0002                        | Enabled                        | Enabled
  PRC0003                        | 1                              | 1
  SETUP001                       | None                           | None
  SETUP002                       | None                           | None
  SETUP003                       | 5                              | 5
  SETUP004                       | On                             | On
  SETUP005                       | True                           | True
  SETUP008                       | Place First                    | Place First
  TCG001                         | Enabled                        | Enabled
  TCG002                         | Enabled                        | Enabled
  TCG003                         | Enable                         | Enable
  TCG004                         | Enable                         | Enable
  TCG006                         | None                           | None
  TCG007                         | None                           | None
  TCG010                         | TCG_2                          | TCG_2
  TCG011                         | Enabled                        | Enabled
  TCG012                         | Enabled                        | Enabled
  TCG013                         | Enabled                        | Enabled
  TCG014                         | CRB                            | CRB
  TCG017                         | Enabled                        | Enabled
  TCG018                         | Enabled                        | Enabled
  TCG019                         | Disabled                       | Disabled
  TCG020                         | Disabled                       | Disabled
  TCG021                         | Disabled                       | Disabled
  TCG022                         | 1.3                            | 1.3
  TCG023                         | Disabled                       | Disabled
  TER001                         | True                           | True
  TER0020                        | 115200                         | 115200
  TER0021                        | 115200                         | 115200
  TER010                         | True                           | True
  TER011                         | VT100+                         | VT100+
  TER012                         | VT100+                         | VT100+
  TER030                         | 8                              | 8
  TER03F                         | None                           | None
  TER04E                         | 1                              | 1
  TER05C                         | None                           | None
  TER05D                         | None                           | None
  TER06B                         | COM1 / SOL                     | COM1 / SOL
  TER06c                         | True                           | True
  TER07B                         | True                           | True
  TER089                         | False                          | False
  TER098                         | ESCN                           | ESCN
  USB003                         | Enabled                        | Enabled
  USB00F                         | Enabled                        | Enabled
```

**Comment by mraineri** [comment]
Great! Thanks for confirming! We'll merge this and make a new release of the tool.
