### ISSUE TITLE
In rf_event_service.py fetching info of SSE information fails 

### ISSUE THREAD

**Issue by rajeshkumarmhpe** [DMTF/Redfish-Tacklebox#59]
Logged in to our product GUI and checked the info.

rf_event_service.py -u <uname> -p <pwd> -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
Traceback (most recent call last):
  File "/usr/local/bin/rf_event_service.py", line 53, in <module>
    redfish_utilities.print_event_subscriptions( event_subscriptions )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/event_service.py", line 145, in print_event_subscriptions
    print( subscription_line_format.format( subscription["Id"], "Destination", subscription["Destination"] ) )
KeyError: 'Destination'

Note:
Logs attached

[Enhancement_request.txt](https://github.com/DMTF/Redfish-Tacklebox/files/7233854/Enhancement_request.txt)

**Comment by mraineri** [comment]
It would certainly be useful if "Destination" was filled in by the service to indicate the client with the open SSE connection so that an administrator could identify which event destination is associated with each client. However, this is not called out today in the schemas, so we need to allow for it in the tool.

**Comment by rajeshkumarmhpe** [comment]
Still we see the same type of issue with fresh clone after the merge.

Logs below:

1. When No subscription: WORKING FINE
===================================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  No subscriptions


2. When one subscription:WORKING FINE
===================================
 rf_event_service.py -u username -p password -r https://x.x.x.x subscribe -dest https://y.y.y.y/redfish_event_handler -c 2
Created subscription '/redfish/v1/EventService/Subscriptions/c30cb7fdefeb453ca2a985935ed4ce16'

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  c30cb7fdefeb453ca2a985935ed4ce16     | Destination: https://y.y.y.y/redfish_event_handler
                                       | State: Enabled
                                       | Context: 2
                                       | Event Format: Event



3. when one subscription already added now open one SSE session: FAILS
===============================================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  c30cb7fdefeb453ca2a985935ed4ce16     | Destination: https://y.y.y.y/redfish_event_handler
                                       | State: Enabled
                                       | Context: 2
                                       | Event Format: Event
Traceback (most recent call last):
  File "/usr/local/bin/rf_event_service.py", line 53, in <module>
    redfish_utilities.print_event_subscriptions( event_subscriptions )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/event_service.py", line 145, in print_event_subscriptions
    print( subscription_line_format.format( subscription["Id"], "Destination", subscription["Destination"] ) )
KeyError: 'Destination'


4. Only with SSE session:FAILS
=========================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
Traceback (most recent call last):
  File "/usr/local/bin/rf_event_service.py", line 53, in <module>
    redfish_utilities.print_event_subscriptions( event_subscriptions )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/event_service.py", line 145, in print_event_subscriptions
    print( subscription_line_format.format( subscription["Id"], "Destination", subscription["Destination"] ) )
KeyError: 'Destination'
