### ISSUE TITLE
Still we see the same type of issue with fresh clone after the fix.

### ISSUE THREAD

**Issue by rajeshkumarmhpe** [DMTF/Redfish-Tacklebox#61]
Still we see the same type of issue with fresh clone after the merge.

Logs below:

1. When No subscription: WORKING FINE
===================================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  No subscriptions

2. When one subscription:WORKING FINE
===================================
 rf_event_service.py -u username -p password -r https://x.x.x.x subscribe -dest https://y.y.y.y/redfish_event_handler -c 2
Created subscription '/redfish/v1/EventService/Subscriptions/c30cb7fdefeb453ca2a985935ed4ce16'

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  c30cb7fdefeb453ca2a985935ed4ce16     | Destination: https://y.y.y.y/redfish_event_handler
                                       | State: Enabled
                                       | Context: 2
                                       | Event Format: Event

3. when one subscription already added now open one SSE session: FAILS
===============================================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
  c30cb7fdefeb453ca2a985935ed4ce16     | Destination: https://y.y.y.y/redfish_event_handler
                                       | State: Enabled
                                       | Context: 2
                                       | Event Format: Event
Traceback (most recent call last):
  File "/usr/local/bin/rf_event_service.py", line 53, in <module>
    redfish_utilities.print_event_subscriptions( event_subscriptions )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/event_service.py", line 145, in print_event_subscriptions
    print( subscription_line_format.format( subscription["Id"], "Destination", subscription["Destination"] ) )
KeyError: 'Destination'

4. Only with SSE session:FAILS
=========================

rf_event_service.py -u username -p password -r https://x.x.x.x info
Service Info
  Status: Enabled
  Delivery Retry Policy: 3 attempts, 60 second intervals
  Event Formats: N/A
  Registries: N/A
  Resource Types: N/A
  Include Origin of Condition Supported: True
  SSE URI: /redfish/v1/EventService/SSE
  SSE Filter Parameters: Unknown/Unspecified

Subscription Info
Traceback (most recent call last):
  File "/usr/local/bin/rf_event_service.py", line 53, in <module>
    redfish_utilities.print_event_subscriptions( event_subscriptions )
  File "/usr/local/lib/python3.9/dist-packages/redfish_utilities/event_service.py", line 145, in print_event_subscriptions
    print( subscription_line_format.format( subscription["Id"], "Destination", subscription["Destination"] ) )
KeyError: 'Destination'

_Originally posted by @rajeshkumarmhpe in https://github.com/DMTF/Redfish-Tacklebox/issues/59#issuecomment-939729779_

**Comment by mraineri** [comment]
Can you please run and send the output of `pip3 show redfish_utilities`? The issue says you cloned the project, but from the console output you've provided, it looks like you're invoking the package that was installed with `pip`. The line numbers in the exception trace don't match the current release of the tool (but they do match what they were prior to the fix being added).
