### ISSUE TITLE
About TransferProtocolType of SimpleUpdate in Update feature

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Tacklebox#65]
Hi,

When I send command for Update feature:
rf_update.py -u Administrator -p superuser -r https://192.168.0.116 -i http://192.168.0.110/rom.ima_enc

>>Traceback (most recent call last):
  File "/usr/local/bin/rf_update.py", line 107, in <module>
    response = redfish_utilities.simple_update( redfish_obj, image_uri, targets = targets )
  File "/usr/local/lib/python3.8/dist-packages/redfish_utilities/update.py", line 125, in simple_update
    verify_response( response )
  File "/usr/local/lib/python3.8/dist-packages/redfish_utilities/messages.py", line 71, in verify_response
    raise RedfishOperationFailedError( "Operation failed: HTTP {}\n{}".format( response.status, exception_string ) )
redfish_utilities.messages.RedfishOperationFailedError: Operation failed: HTTP 400
The property TransferProtocol is a required property and must be included in the request.
The property TransferProtocol is a required property and must be included in the request.

I know "TransferProtocol" is not a required parameter in SimpleUpschemas.  If I want to update image with HTTP protocol, how do I add TransferProtocol property in the request? Is it possible to add a concept similar to default values?

Thanks.

**Comment by mraineri** [comment]
That shouldn't be necessary to add TransferProtocol for that support. TransferProtocol is only needed if it's not possible to encode the protocol in the scheme of the URI. The description for the parameter recommends ignoring the parameter if the scheme in the URI is provided:
>  Services should ignore this parameter if the URI provided in ImageURI contains a scheme.

So, if you want to use HTTP for getting the image, what you have shown in your example should be all you need.

**Comment by FelixD999** [comment]
Got it!
Thanks for your reply.
