### ISSUE TITLE
RFE: Get the power state of ComputerSystems/Chassis

### ISSUE THREAD

**Issue by arnewiebalck** [DMTF/Redfish-Tacklebox#69]
Hi,

It would be great if Redfish-Tacklebox would provide a way to get the power state of a ComputerSystem/Chassis
(similar to 'chassis power status' in a well-known other tool and protocol).

This is a common use case to help users to verify the power state before and after reset commands.

Thanks for considering!
 Arne

**Comment by mraineri** [comment]
@arnewiebalck would extending rf_power_reset.py to show state info? Currently the `--info` parameter just shows the allowable reset/power operations, but we could also have it show the power state. For example:

```
rf_power_reset.py -r <BMC_ADDR> -u <USER> -p <PASS> --info
Supported reset types: On, ForceOff, ForceRestart, GracefulRestart, GracefulShutdown, PushPowerButton, Nmi, PowerCycle
Current Power State: On
```

**Comment by arnewiebalck** [comment]
@mraineri Yes, that would do: this is mostly for interactive use. Thanks!
