### ISSUE TITLE
Boot Override documentation

### ISSUE THREAD

**Issue by StackKorora** [DMTF/Redfish-Tacklebox#76]
https://github.com/DMTF/Redfish-Tacklebox/blob/master/README.md

Boot Override section says:

> --target TARGET, -t TARGET
                        The target boot device; if not provided the tool will
                        display the current boot settings

```
$ rf_boot_override.py -u myuser -p mypass -r https://my.ip.addr -t
usage: rf_boot_override.py [-h] --user USER --password PASSWORD --rhost RHOST
                           [--system SYSTEM] [--info] [--target TARGET]
                           [--uefi UEFI] [--mode MODE] [--reset]
rf_boot_override.py: error: argument --target/-t: expected one argument
```
I was expecting it to display the current boot settings, not tell me I need an argument. :-)

**Comment by mraineri** [comment]
When you specify `-t`, that means you're attempting to set a boot override target. The entire argument needs to be omitted.

**Comment by StackKorora** [comment]
Ah! Thank you. Maybe this could be clearer then?
"If this option is omitted the tool will..."
Or maybe it's just me who reads this and thinks it is just the argument. :man_shrugging: 
Thanks!

**Comment by mraineri** [comment]
Sure, can reword it like that
