### ISSUE TITLE
rf_sensor_list

### ISSUE THREAD

**Issue by wfPyth** [DMTF/Redfish-Tacklebox#83]
Traceback (most recent call last):
      File "/usr/local/bin/rf_sensor_list.py", line 31, in <module>
        sensors = redfish_utilities.get_sensors( redfish_obj )
      File "/usr/local/lib/python3.8/site-packages/redfish_utilities/sensors.py", line 52, in get_sensors
        get_excerpt_status( chassis_instance["ChassisName"], "TemperatureCelsius", "Cel", environment.dict, chassis_instance["Readings"] )
      File "/usr/local/lib/python3.8/site-packages/redfish_utilities/sensors.py", line 347, in get_excerpt_status
        "Reading": object[field]["Reading"],
    KeyError: 'Reading'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
I don't know the reason for the error. If you know, please help to check it. Thank you

**Comment by mraineri** [comment]
Are you able to provide the EnvironmentMetrics resource for your Chassis? The error suggests it's not populating mandatory properties. Having the payload would help determine if this is the cause, and I should be able to add better error handling in these cases so it doesn't crash.

**Comment by wfPyth** [comment]
> 您能否为您的机箱提供 EnvironmentMetrics 资源？该错误表明它没有填充强制属性。拥有有效负载将有助于确定这是否是原因，并且我应该能够在这些情况下添加更好的错误处理，这样它就不会崩溃。

Thank you very much     I'm trying to manually test the return to 'Reading'   
 perform rf_sensor_list.py -u USERName -p Password -r hostName 
this is a ''flex'' machine    I still don't understand what mistake this is

**Comment by jautor** [comment]
Could you show us the JSON response from `/redfish/v1/Chassis/<< Chassis ID >>/EnvironmentMetrics` so we can see what property is missing from that resource?

**Comment by wfPyth** [comment]
this is   -->/redfish/v1/Chassis/1/EnvironmentMetrics
{
    "@odata.id": "/redfish/v1/Chassis/1/EnvironmentMetrics",
    "@odata.context": "/redfish/v1/$metadata#EnvironmentMetrics.EnvironmentMetrics",
    "@odata.etag": "\"38baab796fc0266644d\"",
    "Id": "EnvironmentMetrics",
    "PowerWatts": {
        "Reading": 260,
        "DataSourceUri": "/redfish/v1/Chassis/1/Sensors/55L0"
    },
    "TemperatureCelsius": {},
    "FanSpeedsPercent": [],
    "Description": "This resource shall represent an environment metrics for a Redfish implementation.",
    "Name": "Chassis Environment Metrics",
    "@odata.type": "#EnvironmentMetrics.v1_2_0.EnvironmentMetrics"
}

**Comment by mraineri** [comment]
Thanks; that does confirm the issue. Showing "TemperatureCelsius" with an empty object isn't valid, but we can certainly enhance the tool to not crash in this case.

**Comment by wfPyth** [comment]
Thank you very much. I tried to get chassis information through Ipmitool, and the problem was solved

**Comment by mraineri** [comment]
@wfPyth would it be possible to try out my branch (Sensor-Property-Hardening) on your system to see if that resolves the issue? The change looks good on my end.

**Comment by wfPyth** [comment]
Thank you. I will try this new branch
