### ISSUE TITLE
About message returned from running rf_sys_inventory

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Tacklebox#93]
Hi,

After sending the command I get the response as shown:
![System Inventory](https://user-images.githubusercontent.com/85208691/203461473-637b86fa-c420-4ce4-9dc0-8cf4ade5c843.JPG)
I don't understand the meaning of the message. Do I need to provide any more information?

Thanks,
Felix

**Comment by mraineri** [comment]
This indicates a coding error where the `get` method is being applied to a Python list. However, based on looking over the code, I don't see any cases in inventory.py where `get` is invoked on a list. There are only two patterns where `get` is used:

* On an object representing the connection to the service, which invokes the HTTP GET request for a resource:
    * Example: line 67 `chassis = context.get( chassis_uri )`
* On an object representing the response data from the service
    * Example: line 202 `"PartNumber": resource.get( "PartNumber", None ),`

Unfortunately I'm not hitting the same exception. I see you've cloned the project; did you make any modifications?

**Comment by mraineri** [comment]
Another thing to help debug this is to comment out lines 45 to 47 of rf_sys_inventory.py; that will remove the generic exception handling block in the script, so we can see the exception trace.
