### ISSUE TITLE
Error return about rf_bios_settings

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-Tacklebox#94]
Hi,

I want to change one of the Attribute value from false to true.
![bios](https://user-images.githubusercontent.com/85208691/203727519-cc56ba0d-5e75-4f4a-aa76-faa7f3f364c4.JPG)
But after sending the command I get the response as shown:
![bios_acpi004_true](https://user-images.githubusercontent.com/85208691/203720883-f91b55ec-b063-487d-9bf9-63f735ae9cf5.JPG)
I'm sure this property existed, but value not changed. 
I don't understand what the response means. Could you help to explain?

Thanks,
Felix

**Comment by mraineri** [comment]
I see the issue; we made changes to migrate away from supplying a flag directly in the library method in favor of a global flag set in the library, but the BIOS script wasn't updated accordingly
